version: '3.8'

x-var: &COMMON
  networks:
    internal:

networks:
  internal:

services:
  nginx-proxy:
    <<: *COMMON
    image: nginxproxy/nginx-proxy:latest
    container_name: nginx-proxy
    hostname: nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  prisma-html:
    <<: *COMMON
    image: nginx:latest
    container_name: prisma-html
    hostname: prisma-html
    volumes:
      - ../../html:/usr/share/nginx/html
      - ./nginx/templates:/etc/nginx/templates
    environment:
      VIRTUAL_HOST: dev.html.prisma.internal
      VIRTUAL_PORT: 80
      ALLOW_ORIGIN: http://dev.prisma.internal
  prisma:
    <<: *COMMON
    build: ../../build
    image: kaduhiro/prisma
    container_name: prisma
    hostname: prisma
    ports:
      - 5555:5555
    volumes:
      - ../..:/app
    working_dir: /app
    environment:
      VIRTUAL_HOST: dev.prisma.internal
      VIRTUAL_PORT: 3000
    command:
      - /bin/sh
      - -c
      - 'yarn && yarn dev'
