version: '3.8'

x-var: &COMMON
  networks:
    internal:

networks:
  internal:
    # name: internal
    # external: true

services:
  prisma:
    <<: *COMMON
    build: ../../build
    image: kaduhiro/prisma
    container_name: prisma
    hostname: prisma
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - ../..:/app
    # environment:
    #   TERM: $TERM
    # restart: always
    # tty: true
    # entrypoint:
    #   - /sbin/tini
    #   - --
    command:
      # - tail
      # - -f
      # - /dev/null
      - /bin/sh
      - -c
      - 'yarn && yarn dev'
