version: '3.8'

x-var: &COMMON
  networks:
    internal:

networks:
  internal:

services:
  prisma:
    <<: *COMMON
    build: ../../build
    image: kaduhiro/prisma
    container_name: prisma
    hostname: prisma
    ports:
      - 3000:3000
    volumes:
      - ../..:/app
    command:
      - /bin/sh
      - -c
      - 'yarn && yarn build && yarn start'
